### ISSUE TITLE
Compile against Swagger 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by jmini** [quen2404/openapi-diff#34]
The master branch uses the last rc release of `swagger-parser-v3` as dependency:

```
<dependency>
    <groupId>io.swagger.parser.v3</groupId>
    <artifactId>swagger-parser-v3</artifactId>
    <version>2.0.0.unblu-3</version>
</dependency>
```

Maybe an other branch (`develop` or `swagger-snapshot`) could be added to this repository in order to use `2.0.0-SNAPSHOT` as dependency:

```
<dependency>
    <groupId>io.swagger.parser.v3</groupId>
    <artifactId>swagger-parser-v3</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
```

This way, when the next rc is released, the necessary work would already be prepared on this new branch. 

The only breaking change I have found so far is:
https://github.com/swagger-api/swagger-core/commit/9674c950f31db17f8ed03728901b00259be477c0

If you are interested, I would submit a Pull Request in order to fix the build for this branch.

**Comment by jmini** [comment]
Corresponding change is here: https://github.com/unblu/openapi-diff/commit/bf94811672924653a5394ae9657d7f1ddd482160

**Comment by quen2404** [comment]
Hi,
yes it's a good idea 👍 
`swagger-snapshot` is a good idea ! 
But why are you removing `allowEmptyValue` change in Header ?

**Comment by jmini** [comment]
I think you need to create the branch. Otherwise, I can not submit a PR against it.

**Comment by quen2404** [comment]
Done.

**Comment by jmini** [comment]
Pull Request: https://github.com/quen2404/openapi-diff/pull/35

**Comment by jmini** [comment]
>  But why are you removing `allowEmptyValue` change in Header ?

The corresponding pull request is here: https://github.com/swagger-api/swagger-core/pull/2693. Maybe you should ask there.

**Comment by jmini** [comment]
Cool there is also CircleCI support for the `swagger-snapshot` branch: https://circleci.com/gh/quen2404/openapi-diff/tree/swagger-snapshot
