### ISSUE TITLE
Update to version 2.0 of swagger-parser

### ISSUE THREAD

**Issue by jmini** [quen2404/openapi-diff#37]
There will be a new release of the swagger parser soon.
https://github.com/swagger-api/swagger-parser/issues/683

It should be integrated on the `master` branch.

Version on branch [`swagger-snapshot`](https://github.com/quen2404/openapi-diff/tree/swagger-snapshot) should be updated to the next SNAPSHOT version

**Comment by quen2404** [comment]
Thank you for this information 👍

**Comment by jmini** [comment]
Next SNAPSHOT version is: `2.0.1-SNAPSHOT`

**Comment by quen2404** [comment]
Yes but the this version doesn't exist currently

**Comment by jmini** [comment]
Set version of swagger-parser on `swagger-snapshot` branch to `2.0.1-SNAPSHOT` => #45
