### ISSUE TITLE
Description & summary of Operations not showing in changelog.

### ISSUE THREAD

**Issue by msnijder30** [quen2404/openapi-diff#60]
### Description
I've been testing what this library can and cannot do, and it appears that it does not keep track of `description` & `summary` of the [operations](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject)?

I have also tested this with the `description` of parameters, and they do update.

It does show the `summary` directly after the path of the operation, but it only shows the latest one and it does not show it has been changed.

### The code
```xml
  /pets/{id}:
    get:
      description: A description    // This is not in changelog when changed
      summary: This is a summary    // This is not in changelog when changed
      operationId: find pet by id
      parameters:
        - name: aaadda
          in: path
          description: Param desc   // This is in changelog when changed
          required: true
          schema:
            type: integer
            format: int64
```

### Question
Am I correct in that those properties are not in the Changelog? Or am I making a mistake.

**Comment by quen2404** [comment]
What kind of changelog ? Html / Cli generation are not up to date, but markdown is.
The library keep track of changes in `description` & `summary`, but this is not reported in the changelog currently. I didn't show this kind of changes in the changelog because it's only descriptive data, not change in the API design.

**Comment by msnijder30** [comment]
I was using `HtmlRender`, I will do a test using `MarkdownRender`.

**Comment by msnijder30** [comment]
`description` is not showing up in `MarkdownRender` either, I think it would be nice to show those changes aswell, if possible

**Comment by quen2404** [comment]
Ok, in my company we only use the Markdown output. I will update HtmlRender to output the same details.
But as i mentionned in my previous response, this kind of changes are only descriptive.
I understand you want to see all changes in the changelog :) So as a compromise, we can add an option to output this kind of descriptive changes in the changelog !

**Comment by msnijder30** [comment]
That would be a great feature I think! Is something like that quick to implement?

**Comment by msnijder30** [comment]
Hi, I had some time and looked into the code and made something. 

## What's new
I've added the classes `OperationMetadataDiff` and `ChangedOperationMetadata`. These classes keep track of changes made in `summary` & `description`. 

I've also added the setting `showChangedMetadata` to `MarkdownRenderer`, which is `false` by default.
If enabled and if there are changes the markdown file looks as follows:

## The changed markdown
#### What's Changed
---

##### `GET` /pets/{id}

> This is a summary

###### Metadata:

Changed summary : `Old summary` to: 
> `This is a summary`

Changed description : `Returns a user based on a single ID, if the user does not have access to the pet` to: 
> `A description`

###### Parameters:

Added: `aaadda` in `path`
> Param desc

Deleted: `id` in `path`
> ID of pet to fetch

## Questions
* What do you think of this suggestion?
* What do you think of the name `metadata` to describe the `summary` & `description`?
* Is the formatting of the markdown correct?
* In `ChangedOperationMetadata#isChanged` I'm not sure if there also should be an `INCOMPATIBLE` option since it is compatible with `OpenAPI 2.0` but not with `OpenAPI 1.2`.

------
Looking forward to your reaction, if you think this is a good idea I'll make a pull request, if you have any suggestion for changes I'll add those.

If you think it's a bad idea that's okay aswell 👍

**Comment by quen2404** [comment]
Thanks. I'll review this shortly

**Comment by msnijder30** [comment]
Any updates on the issue?

**Comment by quen2404** [comment]
Hello, i opened the project this morning ! 
I'm working on it !

**Comment by quen2404** [comment]
I'm working on it in the branch [feature/summary-description](https://github.com/quen2404/openapi-diff/tree/feature/summary-description), but work is in progress.

**Comment by msnijder30** [comment]
That sounds good, I was interested in those items mostly but it seems only logical to do it for more items than just `Operation` indeed 👍

**Comment by quen2404** [comment]
Fixed with pull request #61 ! :smile:

**Comment by quen2404** [comment]
@msnijder30 i only add support in diff result, not on the ouput (markdown, html, console). Because i'm working on another branch to improve the output globally (not only for summary/description)

**Comment by msnijder30** [comment]
Okay, perfect! Thanks a lot for this feature. 
I was also wondering if the latest snapshot build was available through maven but I was not able to find it on the snapshot repository, am I overlooking something?

**Comment by quen2404** [comment]
Snapshot version is not available currently 😐

**Comment by msnijder30** [comment]
Any idea when the next snapshot/official version release will be?

**Comment by quen2404** [comment]
Ii  don't know, i have some idea to improve code, and it will break the current api. So want to make this changes before release 2.0.0 ! Not big changes, but enoughts to break compatibility !
