### ISSUE TITLE
RequestBody changes with metadata only changes (i.e. description) causes nullpointer exception

### ISSUE THREAD

**Issue by jinta** [quen2404/openapi-diff#64]
When specifiying a Markdown file output and only changing the description under a requestBody the application fails with a NullPointerException in this bit of code
```java
if (operation.resultRequestBody().isDifferent()) {
  details
           .append(titleH5("Request:"))
           .append(bodyContent(operation.getRequestBody().getContent()));
}
```
It recognises the operation to have changed but the content of the getRequestBody is null in this scenario.

A potential fix is to have a null check in the bodyContent method i.e.:
```java
protected String bodyContent(String prefix, ChangedContent changedContent){
  if (changedContent == null) {
    return ""; // or prefix?
  }
  ...
}
```

**Comment by quen2404** [comment]
Hello @jinta ! Thank your for the issue. Fixed with PR #65
