### ISSUE TITLE
Wrong handling for components/headers in RefPointer

### ISSUE THREAD

**Issue by radup** [quen2404/openapi-diff#66]
Resolving ref in case of components/headers is constructing wrong map in RefPointer class: 
`case HEADERS:
        return (Map<String, T>) components.getSchemas();`

**Comment by radup** [comment]
btw, fix is trivial ofc: `case HEADERS:
        return (Map<String, T>) components.getHeaders();`

**Comment by quen2404** [comment]
Thank you for the feedback, fixed with PR #67 !
