### ISSUE TITLE
README Still References Original Project

### ISSUE THREAD

**Issue by stt19** [quen2404/openapi-diff#69]
HTML Render difference still using swagger-diff's css. 

I figure if you're going to try to pass off the original project's work as your own without giving it any credit, you may as well go ahead and make sure you host the css yourself as well.

https://github.com/Sayi/swagger-diff

Seriously lol... not even in thanks section of the README... smh

**Comment by quen2404** [comment]
Yes html render use swagger-diff css. The css theme used in https://github.com/Sayi/swagger-diff was good, so why should i not use it ?
Please, look at the code before saying i steal the work of someone. I only used the project swagger-diff as source of inspiration to make this tool, but the project content is clearly different. 
But you're right, i should add it in the README.

**Comment by quen2404** [comment]
Fixed with commit [2128208](https://github.com/quen2404/openapi-diff/commit/2128208579aa8fc7c5e249346a0d2622ef09bce0)
